<?php

declare(strict_types = 1);

require_once __DIR__ . '/ABot.php.inc';
require_once __DIR__ . '/AHandler.php.inc';
require_once __DIR__ . '/Handler/AMessageHandler.php.inc';
require_once __DIR__ . '/Handler/ACommandHandler.php.inc';
require_once __DIR__ . '/Handler/ACallbackQueryHandler.php.inc';
require_once __DIR__ . '/Handler/AInlineQueryHandler.php.inc';
require_once __DIR__ . '/Handler/AChosenInlineResultHandler.php.inc';
